### ISSUE TITLE
Installation and Configuration GUIDE

### ISSUE THREAD

**Issue by kumters** [BattleBas/octoprint-telegraf-plugin#5]
Hello, my friend, I just find your plugin and it looks perfect for my dashboard and 3 printers:) I'm a technical guy but not a programmer so I'm not able to deploy this plugin to my telegraf server. I did git clone, but when I run ./deploy.sh it will give me only error messages:

**kumters@influxdb20:~/octoprint-telegraf-plugin$ ./deploy.sh
Building the plugin...
env: ‘go’: No such file or directory
Deploying the plugin...
ssh: Could not resolve hostname pi: Temporary failure in name resolution
ssh: Could not resolve hostname pi: Temporary failure in name resolution
lost connection
ssh: Could not resolve hostname pi: Temporary failure in name resolution**

I checked that deploy script and it looks like it needs "go" and probably it needs to hook up somehow to the main telegraf.conf?

**Comment by sspaink** [comment]
Thank you for trying out this plugin. So I didn't intend the "deploy.sh" to be ready to use for everyone but serve more as an example.

To explain the errors you are seeing. 

- This project is built using the programming language [Go](https://golang.org/), so in order to build it you will need it installed. 
- The hostname `pi` is an alias for the hostname for my Raspberry Pi which I have Telegraf running on. You will need Telegraf hosted on a device connected to your 3d printer.

It sounds like you already have Telegraf setup so that is great, if you haven't deployed an external plugin before I recommend checking out the official documention which has good details describing making/deploying one: https://github.com/influxdata/telegraf/blob/master/docs/EXTERNAL_PLUGINS.md

Essentially you need to do the following:

1. Build the project
  * If using a Raspberry Pi you can use `env GOOS=linux GOARCH=arm GOARM=5 go build -o bin/octoprint cmd/main.go`
2. Copy the resulting binary over to your server running Telegraf
3. Then refer to the config section in the [Readme.md](https://github.com/BattleBas/octoprint-telegraf-plugin#configuration) for details in configuring the plugin.

Hopefully that makes sense? I can keep this issue open to remind myself to write a more thorough step-by-step tutorial in the future, but I don't have time at the moment to write this documentation. Feel free to contribute, pull requests welcome.
